contact_email: cyrus.stoller+cupid@gmail.com

google_analytics:
  development: UA-XXXXXXXX-X
  test: UA-XXXXXXXX-Y
  staging: UA-XXXXXXXX-Z
  production: UA-40142348-2
  domain: cupid.cyrusstoller.com